#!/usr/bin/env bash
# One-off: audit plugin GitHub archived status via gh CLI
set -euo pipefail

repos=(
  "akinsho/bufferline.nvim"
  "akinsho/toggleterm.nvim"
  "Bilal2453/luvit-meta"
  "b0o/schemastore.nvim"
  "catppuccin/nvim"
  "echasnovski/mini.icons"
  "echasnovski/mini.starter"
  "folke/lazy.nvim"
  "folke/lazydev.nvim"
  "folke/noice.nvim"
  "folke/persistence.nvim"
  "folke/snacks.nvim"
  "folke/which-key.nvim"
  "hedyhli/outline.nvim"
  "hrsh7th/cmp-buffer"
  "hrsh7th/cmp-cmdline"
  "hrsh7th/cmp-nvim-lsp"
  "hrsh7th/cmp-path"
  "hrsh7th/nvim-cmp"
  "jay-babu/mason-nvim-dap.nvim"
  "jbyuki/one-small-step-for-vimkind"
  "L3MON4D3/LuaSnip"
  "lewis6991/gitsigns.nvim"
  "lukas-reineke/indent-blankline.nvim"
  "m4xshen/hardtime.nvim"
  "mfussenegger/nvim-dap"
  "MunifTanjim/nui.nvim"
  "neovim/nvim-lspconfig"
  "NickvanDyke/opencode.nvim"
  "numToStr/Comment.nvim"
  "nvim-lua/plenary.nvim"
  "nvim-lualine/lualine.nvim"
  "nvim-neo-tree/neo-tree.nvim"
  "nvim-neotest/nvim-nio"
  "nvim-pack/nvim-spectre"
  "nvim-telescope/telescope-fzf-native.nvim"
  "nvim-telescope/telescope.nvim"
  "nvim-tree/nvim-web-devicons"
  "neovim-treesitter/nvim-treesitter"
  "nvzone/typr"
  "nvzone/volt"
  "onsails/lspkind.nvim"
  "rafamadriz/friendly-snippets"
  "rcarriga/nvim-dap-ui"
  "rcarriga/nvim-notify"
  "saadparwaiz1/cmp_luasnip"
  "sphamba/smear-cursor.nvim"
  "stevearc/conform.nvim"
  "stevearc/overseer.nvim"
  "theHamsta/nvim-dap-virtual-text"
  "WhoIsSethDaniel/mason-tool-installer.nvim"
  "mason-org/mason-lspconfig.nvim"
  "mason-org/mason.nvim"
  "windwp/nvim-autopairs"
)

for repo in "${repos[@]}"; do
  gh api "repos/${repo}" --jq '.full_name + "|" + (.archived|tostring) + "|" + .pushed_at' 2>/dev/null || echo "${repo}|ERROR|"
  sleep 0.12
done
